"""update_season

Revision ID: 3ad0fa3d9e17
Revises: 8ebb56b6e151
Create Date: 2025-02-14 19:32:27.979170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad0fa3d9e17'
down_revision: Union[str, None] = '8ebb56b6e151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('season', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_index('year_index', table_name='season')
    op.create_index('season_time_index', 'season', ['start_time', 'end_time'], unique=False)
    op.drop_column('season', 'start_year')
    op.drop_column('season', 'end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('end_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('season', sa.Column('start_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_index('season_time_index', table_name='season')
    op.create_index('year_index', 'season', ['start_year', 'end_year'], unique=False)
    op.drop_column('season', 'end_time')
    op.drop_column('season', 'start_time')
    # ### end Alembic commands ###
