"""empty message

Revision ID: 55c883470d4b
Revises: ab58835cfc1f
Create Date: 2025-03-05 07:26:50.787280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c883470d4b'
down_revision: Union[str, None] = 'ab58835cfc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stat', sa.Column('transfer_value', sa.Integer(), nullable=True))
    op.drop_column('player_stat', 'tansfer_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stat', sa.Column('tansfer_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player_stat', 'transfer_value')
    # ### end Alembic commands ###
