"""empty message

Revision ID: 5a11e27a2951
Revises: c41bd2587a5b
Create Date: 2025-03-05 00:17:37.628952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a11e27a2951'
down_revision: Union[str, None] = 'c41bd2587a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('calendar', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_game_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_game_stat', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.add_column('season', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('season', sa.Column('end_date', sa.Date(), nullable=False))
    op.drop_index('season_time_index', table_name='season')
    op.create_index('season_time_index', 'season', ['start_date', 'end_date'], unique=False)
    op.drop_column('season', 'start_time')
    op.drop_column('season', 'end_time')
    op.alter_column('standings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stat_game', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stat_game', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('standings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.add_column('season', sa.Column('end_time', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('season', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index('season_time_index', table_name='season')
    op.create_index('season_time_index', 'season', ['start_time', 'end_time'], unique=False)
    op.drop_column('season', 'end_date')
    op.drop_column('season', 'start_date')
    op.alter_column('player_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               nullable=True)
    op.alter_column('player_game_stat', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('player_game_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('calendar', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('calendar', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    # ### end Alembic commands ###
