"""update coach_game

Revision ID: 81e463cd0684
Revises: d14ad3485da0
Create Date: 2025-03-05 02:52:27.618487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e463cd0684'
down_revision: Union[str, None] = 'd14ad3485da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_game', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'coach_game', 'team', ['team_id'], ['team_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coach_game', type_='foreignkey')
    op.drop_column('coach_game', 'team_id')
    # ### end Alembic commands ###
