"""first_migration

Revision ID: 8ebb56b6e151
Revises: 
Create Date: 2025-02-13 21:03:34.476722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebb56b6e151'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('coach_id')
    )
    op.create_table('goal_type',
    sa.Column('goal_type_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('goal_type_id')
    )
    op.create_table('penalty_type',
    sa.Column('penalty_type_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('penalty_type_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('referee',
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('referee_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('season',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.String(length=4), nullable=False),
    sa.Column('end_year', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index('year_index', 'season', ['start_year', 'end_year'], unique=False)
    op.create_table('status_game',
    sa.Column('status_game_id', sa.Integer(), nullable=False),
    sa.Column('status_game', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('status_game_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('name_index', 'team', ['name'], unique=False)
    op.create_table('calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('left_team_id', sa.Integer(), nullable=False),
    sa.Column('right_team_id', sa.Integer(), nullable=False),
    sa.Column('status_game_id', sa.Integer(), nullable=False),
    sa.Column('tour', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('left_team_score', sa.Integer(), nullable=False),
    sa.Column('right_team_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['left_team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_game_id'], ['status_game.status_game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('player_game_stat',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('game_minutes', sa.Integer(), nullable=False),
    sa.Column('start_count', sa.Integer(), nullable=False),
    sa.Column('in_change_count', sa.Integer(), nullable=False),
    sa.Column('change_output_count', sa.Integer(), nullable=False),
    sa.Column('reserve_count', sa.Integer(), nullable=False),
    sa.Column('regular_goal', sa.Integer(), nullable=False),
    sa.Column('penalties_goal', sa.Integer(), nullable=False),
    sa.Column('missed_goal', sa.Integer(), nullable=False),
    sa.Column('yellow_card', sa.Integer(), nullable=False),
    sa.Column('double_yellow_card', sa.Integer(), nullable=False),
    sa.Column('red_card', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'team_id')
    )
    op.create_table('player_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('tansfer_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_stat_id')
    )
    op.create_table('standings',
    sa.Column('standings_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('draw_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('scored_goal', sa.Integer(), nullable=False),
    sa.Column('missed_goal', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('standings_id')
    )
    op.create_table('coach_game',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.coach_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id', 'coach_id')
    )
    op.create_table('goal_game',
    sa.Column('goal_game_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('goal_player_id', sa.Integer(), nullable=False),
    sa.Column('pass_player_id', sa.Integer(), nullable=True),
    sa.Column('goal_type_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_type_id'], ['goal_type.goal_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pass_player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_game_id')
    )
    op.create_table('penalty_game',
    sa.Column('penalty_game_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['penalty_type_id'], ['penalty_type.penalty_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('penalty_game_id')
    )
    op.create_table('player_structure',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.Integer(), nullable=False),
    sa.Column('end_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id', 'team_id', 'player_id')
    )
    op.create_table('referee_game',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referee_id'], ['referee.referee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id', 'referee_id')
    )
    op.create_table('stat_game',
    sa.Column('stat_game_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('outs', sa.Integer(), nullable=False),
    sa.Column('blocked_shots', sa.Integer(), nullable=False),
    sa.Column('shots_from_goal', sa.Integer(), nullable=False),
    sa.Column('free_kicks', sa.Integer(), nullable=False),
    sa.Column('ball_possession_percent', sa.Integer(), nullable=False),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('corners', sa.Integer(), nullable=False),
    sa.Column('shots_hit_post', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('shots_on_goal', sa.Integer(), nullable=False),
    sa.Column('goal_scoring_chances', sa.Integer(), nullable=False),
    sa.Column('dangerous_moments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat_game')
    op.drop_table('referee_game')
    op.drop_table('player_structure')
    op.drop_table('penalty_game')
    op.drop_table('goal_game')
    op.drop_table('coach_game')
    op.drop_table('standings')
    op.drop_table('player_stat')
    op.drop_table('player_game_stat')
    op.drop_table('calendar')
    op.drop_index('name_index', table_name='team')
    op.drop_table('team')
    op.drop_table('status_game')
    op.drop_index('year_index', table_name='season')
    op.drop_table('season')
    op.drop_table('role')
    op.drop_table('referee')
    op.drop_table('player')
    op.drop_table('penalty_type')
    op.drop_table('goal_type')
    op.drop_table('coach')
    # ### end Alembic commands ###
